#!/usr/bin/env lua

package.cpath = package.cpath .. ";/Users/deevs/.local/share/sketchybar_lua/?.so"

-- Require the sketchybar module first
sbar = require("sketchybar")

-- Load helpers and prepare the helper binaries
require("helpers")

-- Bundle the entire initial configuration into a single message to sketchybar
sbar.begin_config()
require("bar")
require("default")
require("items")
sbar.end_config()

-- Run the event loop of the sketchybar module
sbar.event_loop()
